os: Windows Server 2012

install:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - "SET PATH=C:\\Program Files (x86)\\Git\\bin;%PATH%"

  # Download Carl Kleffner's mingw-w64 static toolchain (gcc, fortran, etc)
  - ps: $dwntool=New-Object System.Net.WebClient
  - ps: $dwntool.DownloadFile("https://bitbucket.org/carlkl/mingw-w64-for-python/downloads/mingwpy_amd64_vc100.7z", "C:\\mingw64py34.7z")
  - 7z x C:\\mmingw64py34.7z -oC:\ > null
  - "SET PATH=C:\\mingwpy\\bin;%PATH%"

  # run the configure script
  - python configure --yacc=bison --cc C:\mingwpy\bin\gcc.exe --cxx C:\mingwpy\bin\g++.exe --fc C:\mingwpy\bin\gfortran.exe --prefix %APPVEYOR_BUILD_FOLDER%\ambermini

  # required gnu tools. make sure we've got them
  - where flex
  - where sed
  - where bison
  - where rm
  - where mingw32-make
  - where ar

  - mingw32-make
  - mingw32-make install

build: false

test_script:
  - ambermini\bin\sqm -h
  - ambermini\bin\antechamber -h
  - ambermini\bin\tleap -h

after_test:
  - 7z a ambermini.zip ambermini\ > null

artifacts:
  - path: ambermini.zip
